# Generated by Django 3.0.3 on 2020-11-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='id',
        ),
        migrations.AddField(
            model_name='profilepic',
            name='sno',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
