# Generated by Django 3.0.3 on 2020-11-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0002_auto_20201110_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='img',
            field=models.ImageField(blank=True, default='man.jpg', null=True, upload_to='pics'),
        ),
    ]
