# Generated by Django 3.0.3 on 2020-11-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0004_auto_20201111_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.TextField()),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_image')),
            ],
        ),
    ]
