# Generated by Django 3.0.3 on 2020-11-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0006_posts_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='cover_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='cover_image'),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='img',
            field=models.ImageField(blank=True, default='user_image.jpg', null=True, upload_to=''),
        ),
    ]
