# Generated by Django 3.0.3 on 2020-11-20 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fbclone', '0009_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('message_field', models.TextField()),
                ('message_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to=settings.AUTH_USER_MODEL)),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
