# Generated by Django 3.0.3 on 2020-11-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0010_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
