# Generated by Django 3.0.3 on 2020-11-21 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fbclone', '0011_auto_20201120_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_likes',
            field=models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
