# Generated by Django 3.0.3 on 2020-12-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbclone', '0012_posts_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='chat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
